# Generated by Django 5.2 on 2025-06-25 21:39

import django.db.models.deletion
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0002_product_summery_description_alter_brand_image_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="image_name",
            field=models.ImageField(
                upload_to=utils.FileUpload.upload_to, verbose_name="تصویر برند کالا"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_name",
            field=models.ImageField(
                upload_to=utils.FileUpload.upload_to, verbose_name="تصویر کالا"
            ),
        ),
        migrations.AlterField(
            model_name="productgallary",
            name="image_name",
            field=models.ImageField(
                upload_to=utils.FileUpload.upload_to, verbose_name="تصویر کالا"
            ),
        ),
        migrations.AlterField(
            model_name="productgallary",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gallery_images",
                to="products.product",
                verbose_name="کالا",
            ),
        ),
        migrations.AlterField(
            model_name="productgroup",
            name="image_name",
            field=models.ImageField(
                upload_to=utils.FileUpload.upload_to, verbose_name="تصویر گروه کالا"
            ),
        ),
        migrations.CreateModel(
            name="FeatureValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value_title",
                    models.CharField(max_length=100, verbose_name="عنوان مقدار"),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_values",
                        to="products.feature",
                        verbose_name="ویژگی ",
                    ),
                ),
            ],
            options={
                "verbose_name": "مقدار ویژگی",
                "verbose_name_plural": "مقادیر ویژگی ها",
            },
        ),
        migrations.AddField(
            model_name="productfeature",
            name="filter_value",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_features",
                to="products.featurevalue",
                verbose_name="مقدار وِزگی برای فیلتر",
            ),
        ),
    ]
