# Generated by Django 5.2 on 2025-07-24 09:35

import django.db.models.deletion
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_brand_image_name_alter_product_brand_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="image_name",
            field=models.ImageField(
                upload_to=utils.FileUpload.upload_to, verbose_name="تصویر برند کالا"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_name",
            field=models.ImageField(
                upload_to=utils.FileUpload.upload_to, verbose_name="تصویر کالا"
            ),
        ),
        migrations.AlterField(
            model_name="productfeature",
            name="filter_value",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="filter_feature_value",
                to="products.featurevalue",
                verbose_name="مقدار ویژگی فیلتر",
            ),
        ),
        migrations.AlterField(
            model_name="productgallary",
            name="image_name",
            field=models.ImageField(
                upload_to=utils.FileUpload.upload_to, verbose_name="تصویر کالا"
            ),
        ),
        migrations.AlterField(
            model_name="productgroup",
            name="image_name",
            field=models.ImageField(
                upload_to=utils.FileUpload.upload_to, verbose_name="تصویر گروه کالا"
            ),
        ),
    ]
