# Generated by Django 5.2 on 2025-08-08 21:28

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0018_product_search_vector_alter_brand_image_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="base_rating",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=3, verbose_name="امتیاز پایه"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="base_rating_weight",
            field=models.PositiveIntegerField(
                default=0, verbose_name="وزن امتیاز پایه"
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="image_name",
            field=models.ImageField(
                upload_to=utils.FileUpload.upload_to, verbose_name="تصویر برند کالا"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_name",
            field=models.ImageField(
                upload_to=utils.FileUpload.upload_to, verbose_name="تصویر کالا"
            ),
        ),
        migrations.AlterField(
            model_name="productgallary",
            name="image_name",
            field=models.ImageField(
                upload_to=utils.FileUpload.upload_to, verbose_name="تصویر کالا"
            ),
        ),
        migrations.AlterField(
            model_name="productgroup",
            name="image_name",
            field=models.ImageField(
                upload_to=utils.FileUpload.upload_to, verbose_name="تصویر گروه کالا"
            ),
        ),
    ]
