# Generated by Django 5.2 on 2025-08-29 12:55

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0030_remove_productgroup_ai_summary_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="image_name",
            field=models.ImageField(
                upload_to=utils.FileUpload.upload_to, verbose_name="تصویر برند کالا"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_name",
            field=models.ImageField(
                upload_to=utils.FileUpload.upload_to, verbose_name="تصویر کالا"
            ),
        ),
        migrations.AlterField(
            model_name="productgallary",
            name="image_name",
            field=models.ImageField(
                upload_to=utils.FileUpload.upload_to, verbose_name="تصویر کالا"
            ),
        ),
        migrations.AlterField(
            model_name="productgroup",
            name="image_name",
            field=models.ImageField(
                upload_to=utils.FileUpload.upload_to, verbose_name="تصویر گروه کالا"
            ),
        ),
    ]
