# Generated by Django 5.2 on 2025-07-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="discount",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="تخفیف روی فاکتور"
            ),
        ),
    ]
