# Generated by Django 5.2 on 2025-08-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_paymenttype_order_description_order_payment_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_state_title",
                    models.CharField(max_length=50, verbose_name="وضعیت سفارش"),
                ),
            ],
            options={
                "verbose_name": "وضعیت سفارش",
                "verbose_name_plural": "انواع وضعیت های سفارش",
            },
        ),
    ]
