# Generated by Django 5.2 on 2025-08-10 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_orderstate"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_state",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_states",
                to="orders.orderstate",
                verbose_name="وضعیت سفارش",
            ),
        ),
    ]
