# Generated by Django 5.2 on 2025-08-10 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_order_order_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders_states",
                to="orders.orderstate",
                verbose_name="وضعیت سفارش",
            ),
        ),
    ]
