# Generated by Django 5.2 on 2025-07-30 22:15

import django.db.models.deletion
import utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "image_name",
                    models.ImageField(
                        upload_to=utils.FileUpload.upload_to, verbose_name="تصویر "
                    ),
                ),
            ],
        ),
    ]
