# Generated by Django 5.0.14 on 2025-04-15 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_username'),
    ]

    operations = [
    ]
