# Generated by Django 5.2 on 2025-07-31 12:31

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customer_image_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="image_name",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=utils.FileUpload.upload_to,
                verbose_name="تصویر ",
            ),
        ),
    ]
