"""
Django settings for Shop project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-eb!rz*(thup%^oj5kje7xei*wc^ma7uh8u9q27*b+bv*(9jzv)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.main.apps.MainConfig',
    'apps.accounts.apps.AccountsConfig',
    'apps.products.apps.ProductsConfig',
    'django_admin_listfilter_dropdown',
    'ckeditor',
    'ckeditor_uploader',
    'django_render_partial',
    'django.contrib.humanize',
]


SILENCED_SYSTEM_CHECKS = ['ckeditor.W001']


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Shop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,"templates/")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.main.views.media_admin'
            ],
        },
    },
]

WSGI_APPLICATION = 'Shop.wsgi.application'
#
#
# DATABASES = {
#     'default': {
#         'ENGINE': 'mssql',  # Use the SQL Server backend for Django
#         'NAME': 'EShopDB',  # Replace with your database name
#         'USER': '',         # Leave empty if using Trusted_Connection (Windows Authentication)
#         'PASSWORD': '',     # Leave empty if using Trusted_Connection
#         'HOST': 'DESKTOP-IO02SIE',  # Replace with your server name
#         'PORT': '',         # Leave empty to use the default port
#         'OPTIONS': {
#             'driver': 'ODBC Driver 17 for SQL Server',  # Specify the ODBC driver
#             'trusted_connection': 'yes',               # Use Windows Authentication
#             'encrypt': 'no',                           # Disable encryption (if not required)
#         },
#     }
# }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',       # Your main database name
        'USER': 'postgres',
        'PASSWORD': '123',
        'HOST': 'localhost',
        'PORT': '5432',
        'OPTIONS': {
            'options': '-c search_path=EShop_DB_P',  # This sets the schema
            'connect_timeout': 5,
        },
    }
}




# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)



MEDIA_URL ="/media/"
MEDIA_ROOT= os.path.join(BASE_DIR,"media")


######################################################
#با دو مور بالایی امکان ذخیره موارد در حافظه بوجود میاید
CKEDITOR_UPLOAD_PATH ='images/ckeditor/upload_files/'
CKEDITOR_ALLOW_NONIMAGE_FILES=False
CKEDITOR_STORAGE_BACKEND = 'django.core.files.storage.FileSystemStorage'
# CKEDITOR_CONFIG ={
#         'default': {
#             'toolbar': 'Custom',
#             'toolbar_Custom': [
#                 ['Bold', 'Italic', 'Underline'],
#                 ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
#                 ['Link', 'Unlink'],
#                 ['RemoveFormat', 'Source']
#             ]
#         },
    
#         'special':
#         {
#             'toolbar':'Special','height':500,
#             'toolbar': 'full',
#             'toolbar_Special':
#                 [ 
#                     ['Bold','Link','Unlink','Image'],
#                     ['CodeSnippet'],
#                 ], 'extraPlugins': ','.join(['çodesnippet','clipboard', ])

                
#         },
        
#         'special_an':
#         {
#             'toolbar':'Special','height':500,
#             'toolbar_Special':
#                 [ 
#                     ['Bold'],
#                     ['CodeSnippet'],
#                 ], 'extraPlugins': ','.join(['çodesnippet', ])

#         }
#     }
######################################################
CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'moono-lisa',
        'toolbar_Basic': [
            ['Source', '-', 'Bold', 'Italic']
        ],
        'toolbar_Full': [
            {'name': 'document', 'items': ['Source', '-', 'Save', 'Preview', 'Print']},
            {'name': 'clipboard', 'items': ['Cut', 'Copy', 'Paste', '-', 'Undo', 'Redo']},
            {'name': 'editing', 'items': ['Find', 'Replace', '-', 'SelectAll']},
            {'name': 'styles', 'items': ['Format', 'Font', 'FontSize']},
            {'name': 'basicstyles', 'items': ['Bold', 'Italic', 'Underline', 'Strike', '-', 'RemoveFormat']},
            {'name': 'colors', 'items': ['TextColor', 'BGColor']},
            {'name': 'paragraph', 'items': [
                'NumberedList', 'BulletedList', '-', 
                'Outdent', 'Indent', '-', 
                'Blockquote', '-', 
                'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock',
                '-', 'BidiLtr', 'BidiRtl'
            ]},
            {'name': 'insert', 'items': ['Image', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar']},
            {'name': 'links', 'items': ['Link', 'Unlink', 'Anchor']},
            {'name': 'tools', 'items': ['Maximize']},
        ],
        'toolbar': 'Full',
        'height': 300,
        'width': '100%',
        'extraPlugins': ','.join([
            'uploadimage',  # آپلود تصویر
            'autogrow',     # تغییر ارتفاع خودکار
            'justify',      # ترازبندی
            'bidi',         # پشتیبانی از متن راست‌به‌چپ و چپ‌به‌راست
        ]),
        'removePlugins': 'resize',
        'autoGrow_minHeight': 300,
        'autoGrow_maxHeight': 600,
        'allowedContent': True,
        'language': 'fa',
    }
}

######################################################





# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# AUTH_USER_MODEL = 'accounts.CustomUser'
AUTH_USER_MODEL = 'accounts.CustomUser'