# Generated by Django 5.2 on 2025-08-01 14:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0012_alter_brand_image_name_alter_product_image_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coupon_code",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="کد تخفیف"
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="تاریخ شروع")),
                ("end_date", models.DateTimeField(verbose_name="تاریخ پایان")),
                (
                    "discount",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="درصد تخفیف",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, verbose_name=",وضعیت فعال بودن کد تخفیف"
                    ),
                ),
            ],
            options={
                "verbose_name": "کد تخفیف",
                "verbose_name_plural": "کدهای تخفیف",
            },
        ),
        migrations.CreateModel(
            name="DiscountBasket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_title",
                    models.CharField(
                        max_length=100, verbose_name="عنوان تخفیف سبد خرید"
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="تاریخ شروع")),
                ("end_date", models.DateTimeField(verbose_name="تاریخ پایان")),
                (
                    "discount",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="درصد تخفیف",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, verbose_name=",وضعیت فعال بودن کد تخفیف"
                    ),
                ),
            ],
            options={
                "verbose_name": "سبد تخفیف",
                "verbose_name_plural": "سبدهای تخفیف",
            },
        ),
        migrations.CreateModel(
            name="DiscountBasketDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_basket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discount_basket_details1",
                        to="discounts.discountbasket",
                        verbose_name="سبد تخفیف",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discount_basket_details2",
                        to="products.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "جزئیات سبد تخفیف",
                "verbose_name_plural": "جزئیات سبدهای تخفیف",
            },
        ),
    ]
