# Generated by Django 5.2 on 2025-08-05 11:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("c_s_f", "0001_initial"),
        ("products", "0015_alter_brand_image_name_alter_product_image_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Scoring",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score_value",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="امتیاز",
                    ),
                ),
                (
                    "register_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ثبت امتیاز"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoring_product",
                        to="products.product",
                        verbose_name="کالا",
                    ),
                ),
                (
                    "scoring_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoring_user1",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name=" کاربر امتیاز دهنده ",
                    ),
                ),
            ],
            options={
                "verbose_name": "امتیاز",
                "verbose_name_plural": "امتیازات",
                "ordering": ["-register_date"],
            },
        ),
    ]
