# Generated by Django 5.2 on 2025-08-06 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("c_s_f", "0003_favorite"),
    ]

    operations = [
        migrations.RenameField(
            model_name="favorite",
            old_name="favoraite_user",
            new_name="favorite_user",
        ),
    ]
