# Generated by Django 5.2 on 2025-08-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="is_widget",
            field=models.BooleanField(default=False),
        ),
    ]
