# Generated by Django 5.2 on 2025-08-11 20:20

import django.utils.timezone
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slider_title1",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="عنوان اسلایدر اول",
                    ),
                ),
                (
                    "slider_title2",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="عنوان اسلایدر دوم",
                    ),
                ),
                (
                    "slider_title3",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="عنوان اسلایدر سوم",
                    ),
                ),
                (
                    "image_name",
                    models.ImageField(
                        upload_to=utils.FileUpload.upload_to,
                        verbose_name="تصویر اسلایدر",
                    ),
                ),
                (
                    "slider_link",
                    models.URLField(blank=True, null=True, verbose_name="لینک"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, verbose_name="فعال/غیرفعال"
                    ),
                ),
                (
                    "register_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ درج"),
                ),
                (
                    "publish_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ انتشار"
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "اسلاید",
                "verbose_name_plural": "اسلاید ها",
            },
        ),
    ]
