# Generated by Django 5.2 on 2025-08-20 00:26

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slider",
            name="image_name",
            field=models.ImageField(
                upload_to=utils.FileUpload.upload_to, verbose_name="تصویر اسلایدر"
            ),
        ),
    ]
